### ISSUE TITLE
Supporting v0.1.1 and upcoming releases

### ISSUE THREAD

**Issue by lissyx** [asticode/go-astideepspeech#1]
It's great that there is a Go binding, however it seems to target v0.1.0. We did a lot of changes now, v0.1.1 is available and current master branch has also a lot of new shining.

Do you have any plan on pushing updates? How can we be of help?

**Comment by asticode** [comment]
@lissyx I'd be happy to push any updates that have been done in v0.1.1. I've taken a (quick) look to the release notes and there doesn't seem to have any C method signatures changes therefore I may just have to update the doc to mention v0.1.1 instead of v0.1.0. Is that the case?

**Comment by lissyx** [comment]
There should have been no breaking change with v0.1.1, as much as I can recall, but current master will :). But v0.1.1 is TensorFlow r1.4, so I don't know how you deal with that part, do you bundle the libs?

**Comment by asticode** [comment]
No, these bindings don't bundle the libs, they offer an interface with the C methods. Therefore if there are no changes to the C methods, only the doc has to be updated.

**Comment by lissyx** [comment]
One thing, but it will be for v0.2.0: we change the visibility, not sure how this impacts you: https://github.com/mozilla/DeepSpeech/commit/ade66b015ded24bbefee9c09bb131e578e055492#diff-0317a0e76ece10e0dba742af310a2362R6
