### ISSUE TITLE
v0.7 available

### ISSUE THREAD

**Issue by lissyx** [asticode/go-astideepspeech#15]
Hello @asticode we have a newer version available, with some API changes :)

**Comment by asticode** [comment]
OK good to know, I won't have much time to work on this, therefore if anybody feels like contributing, I'm welcoming PRs

**Comment by lissyx** [comment]
Unfortunately we are all overloaded, I don't think we can make a PR.

**Comment by derat** [comment]
I'm finishing up a local change to do this and will send a PR soon.

**Comment by asticode** [comment]
Thanks for the great PR, it has been merged.
