### ISSUE TITLE
error in "go get go get -u github.com/asticode/go-astideepspeech/...     "

### ISSUE THREAD

**Issue by jjdisplay** [asticode/go-astideepspeech#19]
Hi

I followed your README.md and got the following error when installing astideepspeech at /tmp/deepspeech directory. Please assist. Many thanks. 

$ go get -u github.com/asticode/go-astideepspeech/...         
go: finding github.com/cryptix/wav latest
go: finding github.com/cheekybits/is latest
 github.com/asticode/go-astideepspeech
ld: library not found for -ldeepspeech
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by asticode** [comment]
Can you paste the ouput of

```shell
$ env
```

**Comment by jjdisplay** [comment]
$ env
TMPDIR=/var/folders/4d/rk775v_d61ddc3m9_rtbtnzr0000gn/T/
XPC_FLAGS=0x0
LaunchInstanceID=14584AA4-D417-4E30-9375-CEB1372FE35F
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.lsds5sTzTQ/Listeners
SECURITYSESSIONID=186a7
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=63D23707-46A8-42BA-90B1-8ACA28C68813
SHELL=/bin/zsh
HOME=/Users/james
LOGNAME=james
USER=james
PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
SHLVL=1
PWD=/tmp/deepspeech/lib/DeepSpeech-0.7.1
OLDPWD=/tmp/deepspeech/lib/DeepSpeech-0.7.1/data
ZSH=/Users/james/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
CGO_LDFLAGS=-L/tmp/deepspeech/lib/
CGO_CXXFLAGS=-I/tmp/deepspeech/include/
LC_CTYPE=UTF-8
_=/usr/bin/env

**Comment by asticode** [comment]
Mmm I don't see the `LD_LIBRARY_PATH` environment variable, are you sure you run `export LD_LIBRARY_PATH=/tmp/deepspeech/lib/:$LD_LIBRARY_PATH` ?

**Comment by jamesee** [comment]
Thanks for pointing out. I kept doing 

$ export LD_LIBRARY_PATH=/tmp/deepspeech/lib/:$LD_LIBRARY_PATH

but my env just cannot show the LD_LIBRARY_PATH. Let me find out what went wrong with my environment.  Cheers,
