### ISSUE TITLE
Updating bindings ?

### ISSUE THREAD

**Issue by lissyx** [asticode/go-astideepspeech#2]
Hello,

We will have 0.4.0 soon, do you still maintain those bindings ? We have a streaming API for some time now, it's quite useful

**Comment by asticode** [comment]
@lissyx I'll have a hard time finding some time to work on this.

I'm welcoming PRs though.

**Comment by lissyx** [comment]
Sure, I know mostly nothing about Go but we can try and help you :)

**Comment by asticode** [comment]
Updating the bindings is mostly writing a `C` wrapper that exposes the common functions that will be usable in `GO`. The `GO` part is not that big.

Let me know.

**Comment by lissyx** [comment]
I have updated that part, but the way to work with go seems to be so strange ... Forced to have stuff in a specific directory? I'm able to `go install` but I still don't see a `deepspeech` binary anywhere :/

**Comment by lissyx** [comment]
Okay, that was me just dumb with go.

**Comment by lissyx** [comment]
https://github.com/asticode/go-astideepspeech/pull/3

**Comment by asticode** [comment]
Closing this now.

Thanks again!
