### ISSUE TITLE
[Question] Does this go-binding utilizes GPU for deepspeech engine?

### ISSUE THREAD

**Issue by virenpawar** [asticode/go-astideepspeech#22]
Mozilla's DeepSpeech has 2 installation method and one of them is using `pip3 install deepspeech-gpu` which does utilization of GPU for transcription engine, does this go-binding offers the same in by default nature or any special way?

**Comment by asticode** [comment]
Although I've never tried it, my guess is that if you link to the GPU deepspeech headers and lib you'll be able to use GPU features.

Indeed, the first step of using `astideepspeech` is [setting up `Deepspeech`](https://github.com/asticode/go-astideepspeech#install-deepspeech). In that step, you have to download a `native_client.<your system>.tar.xz`-like file matching your system, therefore if you download the [native_client.amd64.cuda.linux.tar.xz](https://github.com/mozilla/DeepSpeech/releases/download/v0.8.0/native_client.amd64.cuda.linux.tar.xz) my guess is that you'll be able to use `astideepspeech` with CUDA on Linux.

Let me know how it goes.

**Comment by virenpawar** [comment]
Thanks for the idea, did the installation in the said method using `native_client.amd64.cuda.linux.tar.xz` from DeepSpeech v8 releases and things are running fine now. Thanks for the help. :+1:
