### ISSUE TITLE
Update with new API

### ISSUE THREAD

**Issue by lissyx** [asticode/go-astideepspeech#7]
We recently merged a PR that exposes new information, via new API calls: https://github.com/mozilla/DeepSpeech/commit/a009361e470b591f20562214122944d9811592ba#diff-0317a0e76ece10e0dba742af310a2362

This allows access to timing information. We have not yet updated our own bindings by exposing this, I can likely try and take care of that here as well.

**Comment by asticode** [comment]
Your PR would be most welcome!

**Comment by lissyx** [comment]
@asticode I should be able to start working on that tomorrow, but I'd welcome any pointers / docs on how to properly expose structures and structures holding pointers to structures in Go, given my lack of knowledge in that language, any example / doc is useful :)

**Comment by asticode** [comment]
Thing is, structures containing C attributes should be handled differently than structures containing Go attributes as far as I'm concerned. 

I'd simply recommend using getters/setters to access/write C attributes withing Go structs.

You can also check out [this link](https://www.callicoder.com/golang-structs/) or [this one](https://gobyexample.com/structs) to learn more about native Go structs.

If anyone else have ideas, we're all ears.

**Comment by lissyx** [comment]
> Thing is, structures containing C attributes should be handled differently than structures containing Go attributes as far as I'm concerned.
> 
> I'd simply recommend using getters/setters to access/write C attributes withing Go structs.

Sounds like what I did for Rust bindings: https://github.com/RustAudio/deepspeech-rs/commit/023dd85f45ccd52d54a0fd7c0f5c3668b77e6900

**Comment by asticode** [comment]
Yeah, sounds like the safest route!

**Comment by lissyx** [comment]
@asticode I'll first fix `FreeString`

**Comment by lissyx** [comment]
@asticode https://stackoverflow.com/questions/28925179/cgo-how-to-pass-struct-array-from-c-to-go I've found that, trying to use however does not lead to something working. Code is available at https://github.com/lissyx/go-astideepspeech/commits/expose-metadata

This slicing "seems" to work, in the sense that it compiles and runs, but trying to range over it, I always get the first item, and looking at pointers it is always the same.

**Comment by lissyx** [comment]
> I always get the first item

That seems not true, I sometime get garbage, but always the same garbage value.

**Comment by lissyx** [comment]
Okay, nevermind, it seems like this was because there was no C defintion being included for `C.struct_MetadataItem`
